version: 0.0
Resources:
  - inputValidatorFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "inputValidator"
        Alias: "inputValidatorAlias"
        CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
