version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Running Tests"
      - cd scripts
      - chmod +x run_tests.sh
      - ./run_tests.sh
      - cd ..
  build:
    commands:
      - echo "Zipping deployment package"
      - cd functions
      - zip -r9 ../input_validator_deployment_package.zip input_validator
      - zip -r9 ../get_results_deployment_package.zip get_results_info
      - zip -r9 ../code_security_validator_deployment_package.zip code_security_validator
      - zip -r9 ../code_complexity_analyzer_deployment_package.zip code_complexity_analyzer
      - zip -r9 ../post_complexity_analyzer_results_deployment_package.zip post_complexity_analyzer_results
      - zip -r9 ../get_result_graph_deployment_package.zip get_result_graph
      - echo "Done"

  post_build:
    commands:
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name input_validator --zip-file fileb://input_validator_deployment_package.zip
      - aws lambda update-function-code --function-name get_results_info --zip-file fileb://get_results_deployment_package.zip
      - aws lambda update-function-code --function-name code_security_validator --zip-file fileb://code_security_validator_deployment_package.zip
      - aws lambda update-function-code --function-name code_complexity_analyzer --zip-file fileb://code_complexity_analyzer_deployment_package.zip
      - aws lambda update-function-code --function-name post_complexity_analyzer_results --zip-file fileb://post_complexity_analyzer_results_deployment_package.zip
      - aws lambda update-function-code --function-name get_result_graph --zip-file fileb://get_result_graph_deployment_package.zip
      - echo "Done"
artifacts:
  files:
    - "**/*"
