version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Running Tests"
      - cd scripts
      - chmod +x run_tests.sh
      - ./run_tests.sh
      - cd ..
  build:
    commands:
      - echo "Zipping deployment package"
      - zip -r9 input_validator_deployment_package.zip functions/input_validator/input_validator.py
      - zip -r9 get_results_deployment_package.zip functions/get_results_info/get_results_info.py
      - zip -r9 code_security_validator_deployment_package.zip functions/code_security_validator/code_security_validator.py
      - zip -r9 code_complexity_analyzer_deployment_package.zip functions/code_complexity_analyzer/code_complexity_analyzer.py
      - zip -r9 post_complexity_analyzer_results_deployment_package.zip functions/post_complexity_analyzer_results/post_complexity_analyzer_results.py
      - zip -r9 get_result_graph_deployment_package.zip functions/get_result_graph/get_result_graph.py
      - echo "Done"

  post_build:
    commands:
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name input_validator --zip-file fileb://input_validator_deployment_package.zip
      - aws lambda update-function-code --function-name get_results_info --zip-file fileb://get_results_deployment_package.zip
      - aws lambda update-function-code --function-name code_security_validator --zip-file fileb://code_security_validator_deployment_package.zip
      - aws lambda update-function-code --function-name code_complexity_analyzer --zip-file fileb://code_complexity_analyzer_deployment_package.zip
      - aws lambda update-function-code --function-name post_complexity_analyzer_results --zip-file fileb://post_complexity_analyzer_results_deployment_package.zip
      - aws lambda update-function-code --function-name get_result_graph --zip-file fileb://get_result_graph_deployment_package.zip
      - echo "Done"
artifacts:
  files:
    - "**/*"
