version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r functions/input_validator/requirements.txt -t input_validator_lib
      - pip install -r functions/get_results_info/requirements.txt -t get_results_lib
      - pip install -r functions/code_security_validator/requirements.txt -t code_security_validator_lib
      - pip install -r functions/code_complexity_analyzer/requirements.txt -t code_complexity_analyzer_lib
      - pip install -r functions/post_complexity_analyzer_results/requirements.txt -t post_complexity_analyzer_results_lib
  pre_build:
    commands:
      - echo "Running Tests"
      - cd scripts
      - chmod +x run_tests.sh
      - ./run_tests.sh
      - cd ..
  build:
    commands:
      - echo "Zipping deployment package"
      - cd input_validator_lib
      - zip -r9 ../input_validator_deployment_package.zip  .
      - cd ../functions/input_validator
      - zip -u ../../input_validator_deployment_package.zip input_validator.py
      - cd ../..
      - cd get_results_lib
      - zip -r9 ../get_results_deployment_package.zip  .
      - cd ../functions/get_results_info
      - zip -u ../../get_results_deployment_package.zip get_results_info.py
      - cd ../..
      - cd code_security_validator_lib
      - zip -r9 ../code_security_validator_deployment_package.zip  .
      - cd ../functions/code_security_validator
      - zip -u ../../code_security_validator_deployment_package.zip code_security_validator.py
      - cd ../..
      - cd code_complexity_analyzer_lib
      - zip -r9 ../code_complexity_analyzer_deployment_package.zip  .
      - cd ../functions/code_complexity_analyzer
      - zip -u ../../code_complexity_analyzer_deployment_package.zip code_complexity_analyzer.py
      - cd ../..
      - cd post_complexity_analyzer_results_lib
      - zip -r9 ../post_complexity_analyzer_results_deployment_package.zip  .
      - cd ../functions/post_complexity_analyzer_results
      - zip -u ../../post_complexity_analyzer_results_deployment_package.zip post_complexity_analyzer_results.py
      - cd ../..

  post_build:
    commands:
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name input_validator --zip-file fileb://input_validator_deployment_package.zip
      - aws lambda update-function-code --function-name get_results_info --zip-file fileb://get_results_deployment_package.zip
      - aws lambda update-function-code --function-name code_security_validator --zip-file fileb://code_security_validator_deployment_package.zip
      - aws lambda update-function-code --function-name code_complexity_analyzer --zip-file fileb://code_complexity_analyzer_deployment_package.zip
      - aws lambda update-function-code --function-name post_complexity_analyzer_results --zip-file fileb://post_complexity_analyzer_results_deployment_package.zip
      - echo "Done"
artifacts:
  files:
    - "**/*"
